[sc4s_panos_traffic]
search = sourcetype=pan:traffic

[sc4s_panos_threat]
search = sourcetype=pan:threat OR sourcetype=pan:wildfire

[sc4s_panos_change]
search = sourcetype=pan:config

[sc4s_panos_authentication]
search = sourcetype=pan:auth OR sourcetype=pan:globalprotect OR sourcetype=pan:userid
