[pan:log]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none
category = Network & Security
pulldown_type = true
EVAL-vendor = coalesce(vendor, "Palo Alto Networks")
EVAL-product = coalesce(product, "PAN-OS")
EVAL-vendor_product = coalesce(vendor_product, "Palo Alto Networks PAN-OS")

[pan:traffic]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none
TIME_FORMAT = %Y/%m/%d %H:%M:%S
MAX_TIMESTAMP_LOOKAHEAD = 32
EVAL-vendor = coalesce(vendor, "Palo Alto Networks")
EVAL-product = coalesce(product, "PAN-OS")
EVAL-vendor_product = coalesce(vendor_product, "Palo Alto Networks PAN-OS")

[pan:threat]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none
TIME_FORMAT = %Y/%m/%d %H:%M:%S
MAX_TIMESTAMP_LOOKAHEAD = 32
EVAL-vendor = coalesce(vendor, "Palo Alto Networks")
EVAL-product = coalesce(product, "PAN-OS")
EVAL-vendor_product = coalesce(vendor_product, "Palo Alto Networks PAN-OS")

[pan:wildfire]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none
TIME_FORMAT = %Y/%m/%d %H:%M:%S
MAX_TIMESTAMP_LOOKAHEAD = 32

[pan:system]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none
TIME_FORMAT = %Y/%m/%d %H:%M:%S
MAX_TIMESTAMP_LOOKAHEAD = 32

[pan:config]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none
TIME_FORMAT = %Y/%m/%d %H:%M:%S
MAX_TIMESTAMP_LOOKAHEAD = 32

[pan:hipmatch]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none

[pan:userid]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none

[pan:globalprotect]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none

[pan:auth]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none

[pan:decryption]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none

[pan:tunnel]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none

[pan:correlation]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none

[pan:iptag]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none

[pan:gtp]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none

[pan:sctp]
SHOULD_LINEMERGE = false
TRUNCATE = 50000
KV_MODE = none
