[eventtype=sc4s_panos_traffic]
network = enabled
communicate = enabled

[eventtype=sc4s_panos_threat]
attack = enabled
ids = enabled
intrusion = enabled
malware = enabled

[eventtype=sc4s_panos_change]
change = enabled
configuration = enabled

[eventtype=sc4s_panos_authentication]
authentication = enabled
