block parser app-postfilter-commvault_commcell-drop-alerts() {
    channel {
        rewrite(r_set_dest_splunk_null_queue);
    };
};

application app-postfilter-commvault_commcell-drop-alerts[sc4s-postfilter] {
    filter {
        message("^Alerts?:" type(pcre));
    };
    parser { app-postfilter-commvault_commcell-drop-alerts(); };
};
