[commvault_commcell]
search = index=commvault (sourcetype=commvault:commcell OR sourcetype=commvault:commcell:*) vendor_product="commvault:commcell"

[commvault_commcell_audit]
search = index=commvault sourcetype=commvault:commcell:audittrail

[commvault_commcell_event]
search = index=commvault sourcetype=commvault:commcell:events

[commvault_commcell_alert]
search = index=commvault sourcetype=commvault:commcell:alerts
