[commvault:commcell]
SHOULD_LINEMERGE = false
KV_MODE = json
AUTO_KV_JSON = true
TRUNCATE = 20000
TIME_PREFIX = "Utctimestamp":"
TIME_FORMAT = %s
MAX_TIMESTAMP_LOOKAHEAD = 10
category = Custom
pulldown_type = true
EVAL-vendor = coalesce(vendor, "Commvault")
EVAL-product = coalesce(product, "CommCell")
EVAL-vendor_product = coalesce(vendor_product, "commvault:commcell")
EVAL-action = coalesce(action, cv_event_type)
EVAL-signature = coalesce(signature, Operation, Description, Alertname)
EVAL-signature_id = coalesce(signature_id, Opid, Eventid, Alertid)
EVAL-severity = coalesce(severity, Severitylevel, Eventseverity, Alertseverity)
EVAL-user = coalesce(user, Username)
EVAL-dest = coalesce(dest, Computer, Clientname)
EVAL-process = coalesce(process, Program)
EVAL-process_id = coalesce(process_id, Jobid)
EVAL-app = coalesce(app, AgentType, "backup")
EVAL-message = coalesce(message, Details, Description, Alertdescription)
FIELDALIAS-commvault_audit_time = Audittime AS audit_time
FIELDALIAS-commvault_alert_time = Alerttime AS alert_time
FIELDALIAS-commvault_occurrence_time = Occurrencetime AS occurrence_time

[commvault:commcell:audittrail]
SHOULD_LINEMERGE = false
KV_MODE = json
AUTO_KV_JSON = true
TIME_PREFIX = "Utctimestamp":"
TIME_FORMAT = %s
EVAL-cv_event_type = coalesce(cv_event_type, "audit")
EVAL-action = coalesce(action, "audit")

[commvault:commcell:events]
SHOULD_LINEMERGE = false
KV_MODE = json
AUTO_KV_JSON = true
TIME_PREFIX = "Utctimestamp":"
TIME_FORMAT = %s
EVAL-cv_event_type = coalesce(cv_event_type, "event")
EVAL-action = coalesce(action, "event")

[commvault:commcell:alerts]
SHOULD_LINEMERGE = false
KV_MODE = json
AUTO_KV_JSON = true
TIME_PREFIX = "Utctimestamp":"
TIME_FORMAT = %s
EVAL-cv_event_type = coalesce(cv_event_type, "alert")
EVAL-action = coalesce(action, "alert")
