[eventtype=commvault_commcell]
backup = enabled
inventory = enabled

[eventtype=commvault_commcell_audit]
audit = enabled
change = enabled

[eventtype=commvault_commcell_alert]
alert = enabled

[eventtype=commvault_commcell_event]
event = enabled
